### ISSUE TITLE
jsclassesへの依存性

### ISSUE THREAD

**Issue by yasunari** [UT-TeX/vodnote#1]
> それはなんか勿体無いですね… 制約撤廃は全く難しくないはずなので，宿題とします:sushi:（何様だ←）

`\inv@mag`を内部処理に使っていることによる依存性があるため，撤廃しなければならない。

**Comment by aminophen** [comment]
ところで \NeedsTeXFormat{pLaTeX2e} なのはなぜでしょう？

**Comment by yasunari** [comment]
私も気づいてはいるのですが，`pdfLaTeX`で処理すると`gray`の指定が効かなくなってしまい，黒い線が出力されましたので，`\NeedsTeXFormat{pLaTeX2e}`としました。時間ができたら対処したいと思います。

**Comment by aminophen** [comment]
> pdfLaTeXで処理するとgrayの指定が効かなくなってしまい，黒い線が出力されました

私のところではそのような現象は起きず，dvipdfmx の時と同じです。仮に本当に pdfLaTeX がダメだとしても，\NeedsTeXFormat{pLaTeX2e} だと XeLaTeX も LuaLaTeX も潰すことになり勿体ないです。

**Comment by yasunari** [comment]
了解しました。`\NeedsTeXFormat{LaTeX2e}`として原因を特定いたします。
